
import { Language, FactionType } from '../domain/types';

export const strings = {
  ko: {
    ui: {
      loading: '이온테이머 로딩 중...',
      main_menu: '메인 메뉴',
      start_game: '게임 시작',
      tamer_lvl: '테이머 레벨',
      gold: '골드',
      party: '파티',
      skills: '스킬',
      shop: '상점',
      quests: '퀘스트',
      collection: '도감',
      debug: '디버그',
      spirit_points: '영혼 포인트',
      back: '뒤로 가기',
      close: '닫기',
      purchase: '구매',
      sell: '판매',
      current_stock: '현재 보유량',
      active: '진행 중',
      completed: '완료됨',
      locked: '잠김',
      evolution_triggered: '진화 발동!',
      select_path: '진화 경로 선택',
      not_now: '나중에',
      required_item: '필요 아이템',
      victory: '승리!',
      defeated: '패배',
      captured: '포획 성공!',
      escaped: '도망침!',
      tamer_commands: '테이머 명령',
      capture: '포획',
      hp: '체력',
      atk: '공격력',
      def: '방어력',
      spd: '속도',
      reset_progress: '모든 데이터 초기화',
      dev_console: '개발자 콘솔',
      language: '언어',
      boss_appeared: '⚠️ 보스가 나타났습니다!',
      reputation: '평판',
      factions: '진영',
      discount: '할인',
      save_game: '게임 저장',
      load_game: '게임 불러오기',
      confirm_save: '진행 상황을 저장하시겠습니까? 기존 세이브 파일이 덮어씌워집니다.',
      confirm_load: '이전 세이브 파일을 불러오시겠습니까? 현재 진행 상황이 손실됩니다.',
      save_success: '게임이 저장되었습니다!',
      save_failed: '저장 실패',
      load_success: '불러오기 완료!',
      no_save: '저장된 게임이 없습니다.',
      back_to_lobby: '로비로 돌아가기',
      quota_exceeded: '저장 공간 부족',
      storage_unavailable: '저장 권한 없음',
      settings: '설정',
      inventory: '인벤토리',
      no_items: '사용 가능한 아이템이 없습니다.',
      use_item: '사용하기',
      choose_tamer: '테이머를 선택하세요',
      choose_starter: '스타터 와일더를 선택하세요',
      select_hero: '영웅 선택',
      confirm_selection: '선택 확정',
      warrior_desc: '용맹한 전사, 높은 공격력을 자랑합니다.',
      scholar_desc: '지혜로운 학자, 전략적인 전투에 능합니다.',
      mystic_desc: '신비로운술사, 영적인 힘을 다룹니다.',
      ranger_desc: '민첩한 정찰병, 빠른 속도로 적을 압도합니다.',
      hp_restored: 'HP {amount} 회복!',
      hp_full: 'HP가 이미 가득 차 있습니다',
      item_used: '{item} 사용!',
    },
    characters: {
      leo: '레오',
      ken: '켄',
      elara: '엘라라',
      zoe: '조이'
    },
    roles: {
      warrior: '전사',
      scholar: '학자',
      mystic: '신비술사',
      ranger: '레인저'
    },
    factions: {
      [FactionType.EMBER_CLAN]: '엠버 클랜',
      [FactionType.TIDE_WATCHERS]: '타이드 워처',
      [FactionType.STORM_HERDERS]: '스톰 허더',
      [FactionType.GLOOM_STALKERS]: '글룸 스토커',
      [FactionType.GLADE_KEEPERS]: '글레이드 키퍼',
    },
    rep_tiers: {
      hated: '증오함',
      hostile: '적대적',
      neutral: '중립',
      friendly: '우호적',
      honored: '친밀함',
      exalted: '추앙받음',
    },
    species: {
      pyrocat: '파이로캣',
      flarelion: '플레어라이언',
      droplet: '물방울',
      mistlynx: '안개링스',
      lunacat: '루나캣',
      thunderhoof: '썬더후프',
      puffle: '푸플',
      ignis: '이그니스',
      flarehide: '플레어하이드',
      volcadragon: '볼카드래곤',
      aqualo: '아쿠알로',
      serpentform: '서펀트폼',
      krakenwhale: '크라켄웨일',
      voltwing: '볼트윙',
      stormhawk: '스톰호크',
      thundernebula: '썬더네뷸라',
    },
    items: {
      potion: '작은 포션',
      potion_desc: '체력을 20 회복합니다.',
      capture_orb: '포획 오브',
      capture_orb_desc: '야생 와일더를 포획하는 데 사용됩니다.',
      sun_stone: '태양의 돌',
      sun_stone_desc: '진화용 아이템.',
      moon_stone: '달의 돌',
      moon_stone_desc: '진화용 아이템.',
      blazing_fang: '타오르는 이빨',
      blazing_fang_desc: '불 속성 공격력 강화.',
      blazing_fang_lore: '천 번의 사냥 끝에 남은 정수.',
      tidal_blade: '파도 베기',
      tidal_blade_desc: '물 속성 공격력 강화.',
      tidal_blade_lore: '심해의 차가움이 깃든 검.',
      storm_scepter: '폭풍의 홀',
      storm_scepter_desc: '전기 속성 속도 강화.',
      storm_scepter_lore: '만지는 순간 짜릿한 전율이 흐릅니다.',
      iron_shell: '강철 껍질',
      iron_shell_desc: '방어력을 크게 올립니다.',
      iron_shell_lore: '무겁지만 확실한 보호.',
      ember_plate: '불꽃 갑옷',
      ember_plate_desc: '불 속성 전용 방어구.',
      ember_plate_lore: '열기를 에너지로 변환합니다.',
      void_armor: '공허의 갑주',
      void_armor_desc: '어둠의 힘을 담은 최강의 방어구.',
      void_armor_lore: '심연이 당신을 지켜줄 것입니다.',
      wind_pendant: '바람의 펜던트',
      wind_pendant_desc: '속도를 높여줍니다.',
      wind_pendant_lore: '미풍의 가벼움.',
      heart_stone: '생명의 돌',
      heart_stone_desc: '최대 체력을 증가시킵니다.',
      heart_stone_lore: '심장 박동을 강화합니다.',
      monster_core: '와일더의 정수',
      monster_core_desc: '제작을 위한 핵심 재료.',
      mystic_powder: '신비한 가루',
      mystic_powder_desc: '마법 가공에 필요한 가루.',
      hardened_bone: '단단한 뼈',
      hardened_bone_desc: '장비 보강용 재료.',
      spirit_essence: '영혼의 정수',
      spirit_essence_desc: '매우 희귀한 영적인 재료.',
      ancient_scrap: '고대 금속 파편',
      ancient_scrap_desc: '잊혀진 기술의 유산.',
    },
    skills: {
      scratch: '할퀴기',
      scratch_desc: '날카로운 발톱으로 공격합니다.',
      ember: '불똥',
      ember_desc: '작은 불꽃을 발사합니다.',
      tackle: '몸통박치기',
      tackle_desc: '기본적인 물리 돌진 공격입니다.',
      bubble: '방울광선',
      bubble_desc: '물방울을 뿜어 공격합니다.',
      fire_blast: '불대문자',
      fire_blast_desc: '거대한 불꽃 파도를 방출합니다.',
      dark_pulse: '악의 파동',
      dark_pulse_desc: '그림자 에너지 파동을 방출합니다.',
      ice_shard: '얼음 뭉치',
      ice_shard_desc: '빠르게 빙결 파편을 발사합니다.',
      cheer: '응원',
      cheer_desc: '공격력을 10초간 5만큼 증가시킵니다.',
      first_aid: '응급처치',
      first_aid_desc: '체력을 25 회복시킵니다.',
      rally: '결집',
      rally_desc: '모든 스킬 쿨타임을 초기화합니다.',
    },
    quests: {
      first_capture: '첫 포획',
      first_capture_desc: '와일더를 처음으로 포획하세요.',
      reach_level_5: '성장하는 테이머',
      reach_level_5_desc: '테이머 레벨 5를 달성하세요.',
    },
    skill_nodes: {
      p_speed_1: '빠른 발걸음',
      p_atk_1: '열기 어린 발톱',
      p_fire_special: '태양의 핵',
      p_dark_special: '달의 장막',
      d_def_1: '유동적 갑옷',
      d_ice: '한기 전이',
      d_mist: '안개 숙련',
      i_atk_1: '불꽃 갈기',
      i_atk_1_desc: '공격력을 5만큼 증가시킵니다.',
      i_blast: '용암 폭발',
      i_blast_desc: '불대문자 스킬을 해제합니다.',
      i_hp_1: '용암 피부',
      i_hp_1_desc: '최대 체력을 30만큼 증가시킵니다.',
      a_def_1: '물결 장막',
      a_def_1_desc: '방어력을 5만큼 증가시킵니다.',
      a_shard: '서리 송곳',
      a_shard_desc: '얼음 뭉치 스킬을 해제합니다.',
      a_healing: '정화',
      a_healing_desc: '최대 체력을 20만큼 증가시킵니다.',
      v_spd_1: '정전기 충전',
      v_spd_1_desc: '속도를 5만큼 증가시킵니다.',
      v_dash: '번개 돌진',
      v_dash_desc: '공격력을 8만큼 증가시킵니다.',
      v_crit: '전압 집중',
      v_crit_desc: '속도를 5만큼 증가시킵니다.',
    }
  },
  en: {
    ui: {
      loading: 'Loading EonTamers...',
      main_menu: 'Main Menu',
      start_game: 'Start Game',
      tamer_lvl: 'Tamer Level',
      gold: 'Gold',
      party: 'Party',
      skills: 'Skills',
      shop: 'Shop',
      quests: 'Quests',
      collection: 'Dex',
      debug: 'Debug',
      spirit_points: 'Spirit Points',
      back: 'Back',
      close: 'Close',
      purchase: 'Purchase',
      sell: 'Sell',
      current_stock: 'Current Stock',
      active: 'Active',
      completed: 'Completed',
      locked: 'Locked',
      evolution_triggered: 'Evolution Triggered!',
      select_path: 'Select Evolution Path',
      not_now: 'Not now',
      required_item: 'Required Item',
      victory: 'Victory!',
      defeated: 'Defeated',
      captured: 'Captured!',
      escaped: 'Escaped!',
      tamer_commands: 'Tamer Commands',
      capture: 'Capture',
      hp: 'HP',
      atk: 'ATK',
      def: 'DEF',
      spd: 'SPD',
      reset_progress: 'Reset All Progress',
      dev_console: 'Dev Console',
      language: 'Language',
      boss_appeared: '⚠️ A Boss Has Appeared!',
      reputation: 'Reputation',
      factions: 'Factions',
      discount: 'Discount',
      save_game: 'Save Game',
      load_game: 'Load Game',
      confirm_save: 'Do you want to save your progress? This will overwrite your existing save.',
      confirm_load: 'Do you want to load your previous save? Current progress will be lost.',
      save_success: 'Game Saved Successfully!',
      save_failed: 'Save Failed',
      load_success: 'Load Complete!',
      no_save: 'No save data found.',
      back_to_lobby: 'Return to Lobby',
      quota_exceeded: 'Storage Quota Exceeded',
      storage_unavailable: 'Storage Unavailable',
      settings: 'Settings',
      inventory: 'Inventory',
      no_items: 'No items to use.',
      use_item: 'Use Item',
      choose_tamer: 'Choose Tamer',
      choose_starter: 'Choose Starter Wilder',
      select_hero: 'Select Hero',
      confirm_selection: 'Confirm Selection',
      warrior_desc: 'Brave warrior, boasts high attack power.',
      scholar_desc: 'Wise scholar, excels in strategic combat.',
      mystic_desc: 'Mystic practitioner, handles spiritual forces.',
      ranger_desc: 'Agile scout, overwhelms enemies with speed.',
      hp_restored: 'Restored {amount} HP!',
      hp_full: 'HP is already full',
      item_used: 'Used {item}!',
    },
    characters: {
      leo: 'Leo',
      ken: 'Ken',
      elara: 'Elara',
      zoe: 'Zoe'
    },
    roles: {
      warrior: 'Warrior',
      scholar: 'Scholar',
      mystic: 'Mystic',
      ranger: 'Ranger'
    },
    factions: {
      [FactionType.EMBER_CLAN]: 'Ember Clan',
      [FactionType.TIDE_WATCHERS]: 'Tide Watchers',
      [FactionType.STORM_HERDERS]: 'Storm Herders',
      [FactionType.GLOOM_STALKERS]: 'Gloom Stalkers',
      [FactionType.GLADE_KEEPERS]: 'Glade Keepers',
    },
    rep_tiers: {
      hated: 'Hated',
      hostile: 'Hostile',
      neutral: 'Neutral',
      friendly: 'Friendly',
      honored: 'Honored',
      exalted: 'Exalted',
    },
    species: {
      pyrocat: 'Pyrocat',
      flarelion: 'Flarelion',
      droplet: 'Droplet',
      mistlynx: 'Mistlynx',
      lunacat: 'Lunacat',
      thunderhoof: 'Thunderhoof',
      puffle: 'Puffle',
      ignis: 'Ignis',
      flarehide: 'Flarehide',
      volcadragon: 'Volcadragon',
      aqualo: 'Aqualo',
      serpentform: 'Serpentform',
      krakenwhale: 'Krakenwhale',
      voltwing: 'Voltwing',
      stormhawk: 'Stormhawk',
      thundernebula: 'Thundernebula',
    },
    items: {
      potion: 'Small Potion',
      potion_desc: 'Heals 20 HP.',
      capture_orb: 'Capture Orb',
      capture_orb_desc: 'Used to capture wild wilders.',
      sun_stone: 'Sun Stone',
      sun_stone_desc: 'Evolutionary item.',
      moon_stone: 'Moon Stone',
      moon_stone_desc: 'Evolutionary item.',
      blazing_fang: 'Blazing Fang',
      blazing_fang_desc: 'Boosts Fire attribute attack.',
      blazing_fang_lore: 'The essence remains after a thousand hunts.',
      tidal_blade: 'Tidal Blade',
      tidal_blade_desc: 'Boosts Water attribute attack.',
      tidal_blade_lore: 'A blade infused with the cold of the deep sea.',
      storm_scepter: 'Storm Scepter',
      storm_scepter_desc: 'Boosts Electric attribute speed.',
      storm_scepter_lore: 'A crackling energy flows through it.',
      iron_shell: 'Iron Shell',
      iron_shell_desc: 'Greatly increases defense.',
      iron_shell_lore: 'Heavy but reliable protection.',
      ember_plate: 'Ember Plate',
      ember_plate_desc: 'Fire attribute exclusive armor.',
      ember_plate_lore: 'Converts heat into energy.',
      void_armor: 'Void Armor',
      void_armor_desc: 'Ultimate armor containing shadow power.',
      void_armor_lore: 'The abyss will watch over you.',
      wind_pendant: 'Wind Pendant',
      wind_pendant_desc: 'Increases speed.',
      wind_pendant_lore: 'The lightness of a breeze.',
      heart_stone: 'Heart Stone',
      heart_stone_desc: 'Increases maximum HP.',
      heart_stone_lore: 'Strengthens the heartbeat.',
      monster_core: 'Wilder Core',
      monster_core_desc: 'Core material for crafting.',
      mystic_powder: 'Mystic Powder',
      mystic_powder_desc: 'Powder for magical processing.',
      hardened_bone: 'Hardened Bone',
      hardened_bone_desc: 'Material for equipment reinforcement.',
      spirit_essence: 'Spirit Essence',
      spirit_essence_desc: 'Extremely rare spiritual material.',
      ancient_scrap: 'Ancient Scrap',
      ancient_scrap_desc: 'Legacy of forgotten technology.',
    },
    skills: {
      scratch: 'Scratch',
      scratch_desc: 'A basic physical scratch.',
      ember: 'Ember',
      ember_desc: 'A small burst of flame.',
      tackle: 'Tackle',
      tackle_desc: 'A basic physical charge.',
      bubble: 'Bubble',
      bubble_desc: 'Shoots a spray of bubbles.',
      fire_blast: 'Fire Blast',
      fire_blast_desc: 'A devastating inferno wave.',
      dark_pulse: 'Dark Pulse',
      dark_pulse_desc: 'Releases a shadow energy wave.',
      ice_shard: 'Ice Shard',
      ice_shard_desc: 'Fire freezing shards rapidly.',
      cheer: 'Cheer',
      cheer_desc: 'Boost ATK by 5 for 10s.',
      first_aid: 'First Aid',
      first_aid_desc: 'Heal monster for 25 HP.',
      rally: 'Rally',
      rally_desc: 'Cleanse all skill cooldowns.',
    },
    quests: {
      first_capture: 'First Capture',
      first_capture_desc: 'Capture your first Wilder.',
      reach_level_5: 'Growing Tamer',
      reach_level_5_desc: 'Reach Tamer level 5.',
    },
    skill_nodes: {
      p_speed_1: 'Swift Paws',
      p_atk_1: 'Heated Claws',
      p_fire_special: 'Solar Core',
      p_dark_special: 'Lunar Shroud',
      d_def_1: 'Fluid Armor',
      d_ice: 'Cold Snap',
      d_mist: 'Mist Mastery',
      i_atk_1: 'Fire Mane',
      i_atk_1_desc: 'Increases Attack by 5.',
      i_blast: 'Magma Burst',
      i_blast_desc: 'Unlocks Fire Blast skill.',
      i_hp_1: 'Lava Skin',
      i_hp_1_desc: 'Increases Max HP by 30.',
      a_def_1: 'Water Veil',
      a_def_1_desc: 'Increases Defense by 5.',
      a_shard: 'Frost Spike',
      a_shard_desc: 'Unlocks Ice Shard skill.',
      a_healing: 'Purification',
      a_healing_desc: 'Increases Max HP by 20.',
      v_spd_1: 'Static Charge',
      v_spd_1_desc: 'Increases Speed by 5.',
      v_dash: 'Spark Dash',
      v_dash_desc: 'Increases Attack by 8.',
      v_crit: 'Voltage Focus',
      v_crit_desc: 'Increases Speed by 5.',
    }
  }
};

export const getTranslation = (lang: Language) => {
  return strings[lang] || strings.ko;
};

export const getReputationTier = (points: number, lang: Language) => {
  const t = getTranslation(lang).rep_tiers;
  if (points >= 1000) return t.exalted;
  if (points >= 500) return t.honored;
  if (points >= 100) return t.friendly;
  if (points >= -100) return t.neutral;
  if (points >= -500) return t.hostile;
  return t.hated;
};

export const getFactionDiscount = (points: number): number => {
  if (points >= 1000) return 0.20; // 20%
  if (points >= 500) return 0.10; // 10%
  if (points >= 100) return 0.05; // 5%
  return 0;
};
