
import { Language, FactionType } from '../domain/types';

export const strings = {
  ko: {
    ui: {
      loading: '이온테이머 로딩 중...',
      main_menu: '메인 메뉴',
      start_game: '게임 시작',
      tamer_lvl: '테이머 레벨',
      gold: '골드',
      party: '파티',
      skills: '스킬',
      shop: '상점',
      quests: '퀘스트',
      collection: '도감',
      debug: '디버그',
      spirit_points: '영혼 포인트',
      back: '뒤로 가기',
      close: '닫기',
      purchase: '구매',
      sell: '판매',
      current_stock: '현재 보유량',
      active: '진행 중',
      completed: '완료됨',
      locked: '잠김',
      evolution_triggered: '진화 발동!',
      select_path: '진화 경로 선택',
      not_now: '나중에',
      required_item: '필요 아이템',
      victory: '승리!',
      defeated: '패배',
      captured: '포획 성공!',
      escaped: '도망침!',
      tamer_commands: '테이머 명령',
      capture: '포획',
      hp: '체력',
      atk: '공격력',
      def: '방어력',
      spd: '속도',
      reset_progress: '모든 데이터 초기화',
      dev_console: '개발자 콘솔',
      language: '언어',
      boss_appeared: '⚠️ 보스가 나타났습니다!',
      reputation: '평판',
      factions: '진영',
      discount: '할인',
      save_game: '게임 저장',
      load_game: '게임 불러오기',
      confirm_save: '진행 상황을 저장하시겠습니까? 기존 세이브 파일이 덮어씌워집니다.',
      confirm_load: '게임을 불러오시겠습니까? 저장되지 않은 진행 상황은 사라집니다.',
      save_success: '게임이 저장되었습니다!',
      load_success: '게임을 성공적으로 불러왔습니다!',
      no_save: '저장된 데이터가 없습니다.',
      settings: '설정',
      inventory: '인벤토리',
      use_item: '사용',
      hp_restored: 'HP {amount} 회복!',
      hp_full: 'HP가 이미 가득 차 있습니다',
      no_monster: '몬스터가 없습니다',
      no_items: '사용할 아이템이 없습니다',
      item_used: '{item} 사용!',
      save_failed: '저장 실패',
      quota_exceeded: '저장 공간이 꽉 찼습니다! 브라우저의 저장 공간을 확보하세요.',
      storage_unavailable: '저장소를 사용할 수 없습니다',
      corrupted_save: '저장 데이터가 손상되었습니다',
    },
    factions: {
      [FactionType.EMBER_CLAN]: '엠버 클랜',
      [FactionType.TIDE_WATCHERS]: '타이드 워처',
      [FactionType.STORM_HERDERS]: '스톰 허더',
      [FactionType.GLOOM_STALKERS]: '글룸 스토커',
      [FactionType.GLADE_KEEPERS]: '글레이드 키퍼',
    },
    rep_tiers: {
      hated: '적대적',
      hostile: '경계',
      neutral: '중립',
      friendly: '우호적',
      honored: '친밀함',
      exalted: '추앙받는',
    },
    species: {
      pyrocat: '파이로캣',
      flarelion: '플레어라이언',
      shadowcat: '섀도우캣',
      droplet: '물방울',
      mistlynx: '안개링스',
      lunacat: '루나캣',
      thunderhoof: '썬더후프',
      puffle: '푸플', // Soft, cute Korean name for fluffy grass creature
    },
    items: {
      potion: '작은 포션',
      potion_desc: '체력을 20 회복합니다.',
      capture_orb: '포획 오브',
      capture_orb_desc: '야생 몬스터를 포획하는 데 사용됩니다.',
      sun_stone: '태양의 돌',
      sun_stone_desc: '진화용 아이템.',
      moon_stone: '달의 돌',
      moon_stone_desc: '진화용 아이템.',
      // Weapons
      blazing_fang: '타오르는 이빨',
      blazing_fang_desc: '불 속성 공격력 강화.',
      blazing_fang_lore: '천 번의 사냥 끝에 남은 정수.',
      tidal_blade: '파도 베기',
      tidal_blade_desc: '물 속성 공격력 강화.',
      tidal_blade_lore: '심해의 차가움이 깃든 검.',
      storm_scepter: '폭풍의 홀',
      storm_scepter_desc: '전기 속성 속도 강화.',
      storm_scepter_lore: '만지는 순간 짜릿한 전율이 흐릅니다.',
      // Armor
      iron_shell: '강철 껍질',
      iron_shell_desc: '방어력을 크게 올립니다.',
      iron_shell_lore: '무겁지만 확실한 보호.',
      ember_plate: '불꽃 갑옷',
      ember_plate_desc: '불 속성 전용 방어구.',
      ember_plate_lore: '열기를 에너지로 변환합니다.',
      void_armor: '공허의 갑주',
      void_armor_desc: '어둠의 힘을 담은 최강의 방어구.',
      void_armor_lore: '심연이 당신을 지켜줄 것입니다.',
      // Accessories
      wind_pendant: '바람의 펜던트',
      wind_pendant_desc: '속도를 높여줍니다.',
      wind_pendant_lore: '미풍의 가벼움.',
      heart_stone: '생명의 돌',
      heart_stone_desc: '최대 체력을 증가시킵니다.',
      heart_stone_lore: '심장 박동을 강화합니다.',
      // Materials
      monster_core: '몬스터 정수',
      monster_core_desc: '제작을 위한 핵심 재료.',
      mystic_powder: '신비한 가루',
      mystic_powder_desc: '마법 가공에 필요한 가루.',
      hardened_bone: '단단한 뼈',
      hardened_bone_desc: '장비 보강용 재료.',
      spirit_essence: '영혼의 정수',
      spirit_essence_desc: '매우 희귀한 영적인 재료.',
      ancient_scrap: '고대 금속 파편',
      ancient_scrap_desc: '잊혀진 기술의 유산.',
    },
    skills: {
      scratch: '할퀴기',
      scratch_desc: '날카로운 발톱으로 공격합니다.',
      ember: '불똥',
      ember_desc: '작은 불꽃을 발사합니다.',
      tackle: '몸통박치기',
      tackle_desc: '기본적인 물리 돌진 공격입니다.',
      bubble: '방울광선',
      bubble_desc: '물방울을 뿜어 공격합니다.',
      fire_blast: '불대문자',
      fire_blast_desc: '거대한 불꽃 파도를 방출합니다.',
      dark_pulse: '악의 파동',
      dark_pulse_desc: '그림자 에너지 파동을 방출합니다.',
      ice_shard: '얼음 뭉치',
      ice_shard_desc: '빠르게 빙결 파편을 발사합니다.',
      cheer: '응원',
      cheer_desc: '공격력을 10초간 5만큼 증가시킵니다.',
      first_aid: '응급처치',
      first_aid_desc: '체력을 25 회복시킵니다.',
      rally: '결집',
      rally_desc: '모든 스킬 쿨타임을 초기화합니다.',
    },
    quests: {
      first_capture: '테이머의 길',
      first_capture_desc: '포획 오브를 사용하여 첫 번째 몬스터를 포획하세요.',
      reach_level_5: '떠오르는 별',
      reach_level_5_desc: '테이머 레벨 5를 달성하여 실력을 증명하세요.',
      collector_beginner: '수집가 101',
      collector_beginner_desc: '3종류 이상의 다양한 몬스터를 포획하세요.',
      gold_saver: '절약하는 테이머',
      gold_saver_desc: '골드를 1000G 이상 모으세요.',
      defeat_lunacat: '밤의 추격자',
      defeat_lunacat_desc: '밤에 필드에 나타나는 희귀한 루나캣을 처치하세요.',
      evolution_master: '변화의 시작',
      evolution_master_desc: '보유한 몬스터를 다음 단계로 진화시키세요.',
    },
    skill_nodes: {
      p_speed_1: '빠른 발걸음',
      p_atk_1: '열기 어린 발톱',
      p_fire_special: '태양의 핵',
      p_dark_special: '달의 장막',
      d_def_1: '유동적 갑옷',
      d_ice: '한기 전이',
      d_mist: '안개 숙련',
    }
  },
  en: {
    ui: {
      loading: 'Loading EonTamers...',
      main_menu: 'Main Menu',
      start_game: 'Start Game',
      tamer_lvl: 'Tamer Level',
      gold: 'Gold',
      party: 'Party',
      skills: 'Skills',
      shop: 'Shop',
      quests: 'Quests',
      collection: 'Dex',
      debug: 'Debug',
      spirit_points: 'Spirit Points',
      back: 'Back',
      close: 'Close',
      purchase: 'Purchase',
      sell: 'Sell',
      current_stock: 'Current Stock',
      active: 'Active',
      completed: 'Completed',
      locked: 'Locked',
      evolution_triggered: 'Evolution Triggered!',
      select_path: 'Select Evolution Path',
      not_now: 'Not now',
      required_item: 'Required Item',
      victory: 'Victory!',
      defeated: 'Defeated',
      captured: 'Captured!',
      escaped: 'Escaped!',
      tamer_commands: 'Tamer Commands',
      capture: 'Capture',
      hp: 'HP',
      atk: 'ATK',
      def: 'DEF',
      spd: 'SPD',
      reset_progress: 'Reset All Progress',
      dev_console: 'Dev Console',
      language: 'Language',
      boss_appeared: '⚠️ A Boss Has Appeared!',
      reputation: 'Reputation',
      factions: 'Factions',
      discount: 'Discount',
      save_game: 'Save Game',
      load_game: 'Load Game',
      confirm_save: 'Do you want to save? Your existing save file will be overwritten.',
      confirm_load: 'Do you want to load? Any unsaved progress will be lost.',
      save_success: 'Game saved successfully!',
      load_success: 'Game loaded successfully!',
      no_save: 'No save data found.',
      settings: 'Settings',
      inventory: 'Inventory',
      use_item: 'Use',
      hp_restored: 'Restored {amount} HP!',
      hp_full: 'HP is already full',
      no_monster: 'No monster available',
      no_items: 'No items to use',
      item_used: 'Used {item}!',
      save_failed: 'Save failed',
      quota_exceeded: 'Storage full! Please free up space in your browser.',
      storage_unavailable: 'Storage unavailable',
      corrupted_save: 'Save data corrupted',
    },
    factions: {
      [FactionType.EMBER_CLAN]: 'Ember Clan',
      [FactionType.TIDE_WATCHERS]: 'Tide Watchers',
      [FactionType.STORM_HERDERS]: 'Storm Herders',
      [FactionType.GLOOM_STALKERS]: 'Gloom Stalkers',
      [FactionType.GLADE_KEEPERS]: 'Glade Keepers',
    },
    rep_tiers: {
      hated: 'Hated',
      hostile: 'Hostile',
      neutral: 'Neutral',
      friendly: 'Friendly',
      honored: 'Honored',
      exalted: 'Exalted',
    },
    species: {
      pyrocat: 'Pyrocat',
      flarelion: 'Flarelion',
      shadowcat: 'Shadowcat',
      droplet: 'Droplet',
      mistlynx: 'Mistlynx',
      lunacat: 'Lunacat',
      thunderhoof: 'Thunderhoof',
      puffle: 'Puffle',
    },
    items: {
      potion: 'Small Potion',
      potion_desc: 'Heals 20 HP.',
      capture_orb: 'Capture Orb',
      capture_orb_desc: 'Used to capture wild monsters.',
      sun_stone: 'Sun Stone',
      sun_stone_desc: 'Evolutionary item.',
      moon_stone: 'Moon Stone',
      moon_stone_desc: 'Evolutionary item.',
      // Weapons
      blazing_fang: 'Blazing Fang',
      blazing_fang_desc: 'Boosts Fire attribute attack.',
      blazing_fang_lore: 'The essence remains after a thousand hunts.',
      tidal_blade: 'Tidal Blade',
      tidal_blade_desc: 'Boosts Water attribute attack.',
      tidal_blade_lore: 'A blade infused with the cold of the deep sea.',
      storm_scepter: 'Storm Scepter',
      storm_scepter_desc: 'Boosts Electric attribute speed.',
      storm_scepter_lore: 'A crackling energy flows through it.',
      // Armor
      iron_shell: 'Iron Shell',
      iron_shell_desc: 'Greatly increases defense.',
      iron_shell_lore: 'Heavy but reliable protection.',
      ember_plate: 'Ember Plate',
      ember_plate_desc: 'Fire attribute exclusive armor.',
      ember_plate_lore: 'Converts heat into energy.',
      void_armor: 'Void Armor',
      void_armor_desc: 'Ultimate armor containing shadow power.',
      void_armor_lore: 'The abyss will watch over you.',
      // Accessories
      wind_pendant: 'Wind Pendant',
      wind_pendant_desc: 'Increases speed.',
      wind_pendant_lore: 'The lightness of a breeze.',
      heart_stone: 'Heart Stone',
      heart_stone_desc: 'Increases maximum HP.',
      heart_stone_lore: 'Strengthens the heartbeat.',
      // Materials
      monster_core: 'Monster Core',
      monster_core_desc: 'Core material for crafting.',
      mystic_powder: 'Mystic Powder',
      mystic_powder_desc: 'Powder for magical processing.',
      hardened_bone: 'Hardened Bone',
      hardened_bone_desc: 'Material for equipment reinforcement.',
      spirit_essence: 'Spirit Essence',
      spirit_essence_desc: 'Extremely rare spiritual material.',
      ancient_scrap: 'Ancient Scrap',
      ancient_scrap_desc: 'Legacy of forgotten technology.',
    },
    skills: {
      scratch: 'Scratch',
      scratch_desc: 'A basic physical scratch.',
      ember: 'Ember',
      ember_desc: 'A small burst of flame.',
      tackle: 'Tackle',
      tackle_desc: 'A basic physical charge.',
      bubble: 'Bubble',
      bubble_desc: 'Shoots a spray of bubbles.',
      fire_blast: 'Fire Blast',
      fire_blast_desc: 'A devastating inferno wave.',
      dark_pulse: 'Dark Pulse',
      dark_pulse_desc: 'Releases a shadow energy wave.',
      ice_shard: 'Ice Shard',
      ice_shard_desc: 'Fire freezing shards rapidly.',
      cheer: 'Cheer',
      cheer_desc: 'Boost ATK by 5 for 10s.',
      first_aid: 'First Aid',
      first_aid_desc: 'Heal monster for 25 HP.',
      rally: 'Rally',
      rally_desc: 'Cleanse all skill cooldowns.',
    },
    quests: {
      first_capture: 'Tamer Path',
      first_capture_desc: 'Capture your first monster using an Orb.',
      reach_level_5: 'Rising Star',
      reach_level_5_desc: 'Reach Tamer level 5 to prove your potential.',
      collector_beginner: 'Collection 101',
      collector_beginner_desc: 'Capture at least 3 different monster species.',
      gold_saver: 'Thrifty Tamer',
      gold_saver_desc: 'Accumulate more than 1000 Gold.',
      defeat_lunacat: 'Night Stalker',
      defeat_lunacat_desc: 'Defeat the rare Lunacat that appears at night.',
      evolution_master: 'Metamorphosis',
      evolution_master_desc: 'Evolve one of your monsters to its next stage.',
    },
    skill_nodes: {
      p_speed_1: 'Swift Paws',
      p_atk_1: 'Heated Claws',
      p_fire_special: 'Solar Core',
      p_dark_special: 'Lunar Shroud',
      d_def_1: 'Fluid Armor',
      d_ice: 'Cold Snap',
      d_mist: 'Mist Mastery',
    }
  }
};

export const getTranslation = (lang: Language) => {
  return strings[lang] || strings.ko;
};

export const getReputationTier = (points: number, lang: Language) => {
  const t = getTranslation(lang).rep_tiers;
  if (points >= 1000) return t.exalted;
  if (points >= 500) return t.honored;
  if (points >= 100) return t.friendly;
  if (points >= -100) return t.neutral;
  if (points >= -500) return t.hostile;
  return t.hated;
};

export const getFactionDiscount = (points: number): number => {
  if (points >= 1000) return 0.20; // 20%
  if (points >= 500) return 0.10; // 10%
  if (points >= 100) return 0.05; // 5%
  return 0;
};
