
import { Language, FactionType } from '../domain/types';

export const strings = {
  ko: {
    ui: {
      loading: '이온테이머 로딩 중...',
      main_menu: '메인 메뉴',
      start_game: '게임 시작',
      tamer_lvl: '테이머 레벨',
      gold: '골드',
      party: '파티',
      skills: '스킬',
      shop: '상점',
      quests: '퀘스트',
      collection: '도감',
      debug: '디버그',
      spirit_points: '영혼 포인트',
      back: '뒤로 가기',
      close: '닫기',
      purchase: '구매',
      sell: '판매',
      current_stock: '현재 보유량',
      active: '진행 중',
      completed: '완료됨',
      locked: '잠김',
      unlocked: '달성',
      pending: '보상 대기',
      evolution_triggered: '진화 발동!',
      select_path: '진화 경로 선택',
      not_now: '나중에',
      required_item: '필요 아이템',
      victory: '승리!',
      defeated: '패배',
      captured: '포획 성공!',
      escaped: '도망침!',
      tamer_commands: '테이머 명령',
      capture: '포획',
      hp: '체력',
      atk: '공격력',
      def: '방어력',
      spd: '속도',
      reset_progress: '모든 데이터 초기화',
      dev_console: '개발자 콘솔',
      language: '언어',
      boss_appeared: '⚠️ 보스가 나타났습니다!',
      reputation: '평판',
      factions: '진영',
      discount: '할인',
      save_game: '게임 저장',
      load_game: '게임 불러오기',
      confirm_save: '진행 상황을 저장하시겠습니까? 기존 세이브 파일이 덮어씌워집니다.',
      confirm_load: '이전 세이브 파일을 불러오시겠습니까? 현재 진행 상황이 손실됩니다.',
      save_success: '게임이 저장되었습니다!',
      save_failed: '저장 실패',
      load_success: '불러오기 완료!',
      no_save: '저장된 게임이 없습니다.',
      back_to_lobby: '로비로 돌아가기',
      quota_exceeded: '저장 공간 부족',
      storage_unavailable: '저장 권한 없음',
      settings: '설정',
      inventory: '인벤토리',
      incubator: '인큐베이터',
      no_items: '사용 가능한 아이템이 없습니다.',
      use_item: '사용하기',
      choose_tamer: '테이머를 선택하세요',
      choose_starter: '스타터 와일더를 선택하세요',
      select_hero: '영웅 선택',
      confirm_selection: '선택 확정',
      warrior_desc: '용맹한 전사, 높은 공격력을 자랑합니다.',
      scholar_desc: '지혜로운 학자, 전략적인 전투에 능합니다.',
      mystic_desc: '신비로운술사, 영적인 힘을 다룹니다.',
      ranger_desc: '민첩한 정찰병, 빠른 속도로 적을 압도합니다.',
      hp_restored: 'HP {amount} 회복!',
      hp_full: 'HP가 이미 가득 차 있습니다',
      item_used: '{item} 사용!',
      quest_completed: '퀘스트 완료!',
      claim_reward: '보상 받기',
      // Phase 4
      achievements: '업적',
      achievement_unlocked: '업적 달성!',
      claim: '수령',
      claimed: '수령 완료',
      progress: '진행도',
      all: '전체',
      daily_login: '출석 체크',
      login_streak: '연속 출석',
      consecutive_days: '{days}일 연속',
      day: '{day}일차',
      todays_reward: '오늘의 보상',
      expeditions: '탐험',
      start_expedition: '탐험 시작',
      select_monsters: '몬스터 선택',
      selected: '선택됨',
      time_remaining: '남은 시간',
      duration: '소요 시간',
      expedition_complete: '탐험 완료!',
      claim_rewards: '보상 받기',
      available: '사용 가능',
      active_expeditions: '진행 중인 탐험',
      requirements: '요구 조건',
      rewards: '보상',
      monsters_required: '{count}마리 필요',
      level_required: 'LV.{level} 이상',
      type_required: '{type} 속성 필요',
    },
    characters: {
      leo: '레오',
      ken: '켄',
      elara: '엘라라',
      zoe: '조이'
    },
    roles: {
      warrior: '전사',
      scholar: '학자',
      mystic: '신비술사',
      ranger: '레인저'
    },
    factions: {
      [FactionType.EMBER_CLAN]: '엠버 클랜',
      [FactionType.TIDE_WATCHERS]: '타이드 워처',
      [FactionType.STORM_HERDERS]: '스톰 허더',
      [FactionType.GLOOM_STALKERS]: '글룸 스토커',
      [FactionType.GLADE_KEEPERS]: '글레이드 키퍼',
    },
    rep_tiers: {
      hated: '증오함',
      hostile: '적대적',
      neutral: '중립',
      friendly: '우호적',
      honored: '친밀함',
      exalted: '추앙받음',
    },
    achievement_categories: {
      combat: '전투',
      collection: '수집',
      progression: '성장',
      economy: '경제',
    },
    species: {
      pyrocat: '파이로캣',
      flarelion: '플레어라이언',
      droplet: '물방울',
      mistlynx: '안개링스',
      lunacat: '루나캣',
      thunderhoof: '썬더후프',
      puffle: '푸플',
      ignis: '이그니스',
      flarehide: '플레어하이드',
      volcadragon: '볼카드래곤',
      aqualo: '아쿠알로',
      serpentform: '서펀트폼',
      krakenwhale: '크라켄웨일',
      voltwing: '볼트윙',
      stormhawk: '스톰호크',
      thundernebula: '썬더네뷸라',
    },
    items: {
      potion: '작은 포션',
      potion_desc: '체력을 20 회복합니다.',
      capture_orb: '포획 오브',
      capture_orb_desc: '야생 와일더를 포획하는 데 사용됩니다.',
      sun_stone: '태양의 돌',
      sun_stone_desc: '진화용 아이템.',
      moon_stone: '달의 돌',
      moon_stone_desc: '진화용 아이템.',
      blazing_fang: '타오르는 이빨',
      blazing_fang_desc: '불 속성 공격력 강화.',
      blazing_fang_lore: '천 번의 사냥 끝에 남은 정수.',
      tidal_blade: '파도 베기',
      tidal_blade_desc: '물 속성 공격력 강화.',
      tidal_blade_lore: '심해의 차가움이 깃든 검.',
      storm_scepter: '폭풍의 홀',
      storm_scepter_desc: '전기 속성 속도 강화.',
      storm_scepter_lore: '만지는 순간 짜릿한 전율이 흐릅니다.',
      iron_shell: '강철 껍질',
      iron_shell_desc: '방어력을 크게 올립니다.',
      iron_shell_lore: '무겁지만 확실한 보호.',
      ember_plate: '불꽃 갑옷',
      ember_plate_desc: '불 속성 전용 방어구.',
      ember_plate_lore: '열기를 에너지로 변환합니다.',
      void_armor: '공허의 갑주',
      void_armor_desc: '어둠의 힘을 담은 최강의 방어구.',
      void_armor_lore: '심연이 당신을 지켜줄 것입니다.',
      wind_pendant: '바람의 펜던트',
      wind_pendant_desc: '속도를 높여줍니다.',
      wind_pendant_lore: '미풍의 가벼움.',
      heart_stone: '생명의 돌',
      heart_stone_desc: '최대 체력을 증가시킵니다.',
      heart_stone_lore: '심장 박동을 강화합니다.',
      monster_core: '와일더의 정수',
      monster_core_desc: '제작을 위한 핵심 재료.',
      mystic_powder: '신비한 가루',
      mystic_powder_desc: '마법 가공에 필요한 가루.',
      hardened_bone: '단단한 뼈',
      hardened_bone_desc: '장비 보강용 재료.',
      spirit_essence: '영혼의 정수',
      spirit_essence_desc: '매우 희귀한 영적인 재료.',
      ancient_scrap: '고대 금속 파편',
      ancient_scrap_desc: '잊혀진 기술의 유산.',
    },
    skills: {
      scratch: '할퀴기',
      scratch_desc: '날카로운 발톱으로 공격합니다.',
      ember: '불똥',
      ember_desc: '작은 불꽃을 발사합니다.',
      tackle: '몸통박치기',
      tackle_desc: '기본적인 물리 돌진 공격입니다.',
      bubble: '방울광선',
      bubble_desc: '물방울을 뿜어 공격합니다.',
      fire_blast: '불대문자',
      fire_blast_desc: '거대한 불꽃 파도를 방출합니다.',
      dark_pulse: '악의 파동',
      dark_pulse_desc: '그림자 에너지 파동을 방출합니다.',
      ice_shard: '얼음 뭉치',
      ice_shard_desc: '빠르게 빙결 파편을 발사합니다.',
      cheer: '응원',
      cheer_desc: '공격력을 10초간 5만큼 증가시킵니다.',
      first_aid: '응급처치',
      first_aid_desc: '체력을 25 회복시킵니다.',
      rally: '결집',
      rally_desc: '모든 스킬 쿨타임을 초기화합니다.',
      // LEO
      leo_rage: '분노의 함성',
      leo_rage_desc: '공격력을 20초간 10만큼 증가시킵니다.',
      leo_iron: '무쇠 의지',
      leo_iron_desc: '방어력을 20초간 10만큼 증가시킵니다.',
      leo_war_cry: '전쟁의 함성',
      leo_war_cry_desc: '공격력을 20초간 30만큼 증가시킵니다.',
      leo_pride: '사자의 자부심',
      leo_pride_desc: '공격력과 방어력을 30초간 20만큼 증가시킵니다.',
      leo_king: '백수의 왕',
      leo_king_desc: '공격력을 15초간 60만큼 증가시킵니다.',
      // KEN
      ken_eye: '전술의 눈',
      ken_eye_desc: '속도를 20초간 15만큼 증가시킵니다.',
      ken_scan: '약점 분석',
      ken_scan_desc: '적의 방어력을 20초간 15만큼 감소시킵니다.',
      ken_command: '정밀 지휘',
      ken_command_desc: '속도를 20초간 30만큼 증가시킵니다.',
      ken_strategy: '대전략',
      ken_strategy_desc: '공격력을 30초간 25만큼 증가시킵니다.',
      // ELARA
      elara_heal: '영혼의 치유',
      elara_heal_desc: '체력을 50 회복시킵니다.',
      elara_regen: '심신의 안정',
      elara_regen_desc: '디버프를 제거하고 10초간 매초 HP를 10 회복합니다.',
      elara_flow: '영혼의 흐름',
      elara_flow_desc: '체력을 150 회복시킵니다.',
      // ZOE
      zoe_wind: '순풍',
      zoe_wind_desc: '속도를 20초간 20만큼 증가시킵니다.',
      zoe_lock: '타겟 고정',
      zoe_lock_desc: '다음 공격력이 10초간 15만큼 증가합니다.',
      zoe_hurricane: '허리케인',
      zoe_hurricane_desc: '속도를 20초간 40만큼 증가시킵니다.',
    },
    quests: {
      first_capture: '첫 포획',
      first_capture_desc: '와일더를 처음으로 포획하세요.',
      reach_level_5: '성장하는 테이머',
      reach_level_5_desc: '테이머 레벨 5를 달성하세요.',
      defeat_lunacat: '루나캣 처치',
      defeat_lunacat_desc: '밤에 나타나는 루나캣을 물리치세요!',
      story_capture_5: '늘어나는 컬렉션',
      story_capture_5_desc: '5종류의 다른 와일더를 포획하세요.',
      reach_level_10: '테이머 견습생',
      reach_level_10_desc: '테이머 레벨 10을 달성하세요.',
      reach_level_20: '프로 테이머',
      reach_level_20_desc: '테이머 레벨 20을 달성하세요.',
      defeat_boss_flarelion: '불의 시련',
      defeat_boss_flarelion_desc: '최종 보스 플레어라이언을 처치하세요.',
      defeat_boss_krakenwhale: '심해의 공포',
      defeat_boss_krakenwhale_desc: '최종 보스 크라켄웨일을 처치하세요.',
      reach_level_50: '전설의 테이머',
      reach_level_50_desc: '최고 레벨 50을 달성하세요.',
      daily_win_3: '오전 훈련',
      daily_win_3_desc: '전투에서 3번 승리하세요.',
      daily_win_5: '전투 숙련자',
      daily_win_5_desc: '전투에서 5번 승리하세요.',
      daily_capture_1: '빠른 포획',
      daily_capture_1_desc: '와일더 1마리를 포획하세요.',
      daily_capture_3: '인재 영입',
      daily_capture_3_desc: '와일더 3마리를 포획하세요.',
      daily_item_use: '정비 시간',
      daily_item_use_desc: '아이템을 5번 사용하세요.',
      daily_item_use_10: '인벤토리 점검',
      daily_item_use_10_desc: '아이템을 10번 사용하세요.',
      daily_spend_100: '단골 손님',
      daily_spend_100_desc: '상점에서 100 골드를 사용하세요.',
      daily_spend_500: '큰 손',
      daily_spend_500_desc: '상점에서 500 골드를 사용하세요.',
      daily_win_fire: '불꽃 끄기',
      daily_win_fire_desc: '불 속성 와일더를 3마리 처치하세요.',
      daily_win_water: '파도 길들이기',
      daily_win_water_desc: '물 속성 와일더를 3마리 처치하세요.',
      daily_win_grass: '잡초 뽑기',
      daily_win_grass_desc: '풀 속성 와일더를 3마리 처치하세요.',
      daily_win_electric: '전류 차단',
      daily_win_electric_desc: '전기 속성 와일더를 3마리 처치하세요.',
      daily_win_neutral: '힘의 균형',
      daily_win_neutral_desc: '노멀 속성 와일더를 3마리 처치하세요.',
      daily_win_dark_light: '황혼의 결투',
      daily_win_dark_light_desc: '어둠 또는 빛 속성 와일더를 3마리 처치하세요.',
      daily_earn_500: '수익 사냥꾼',
      daily_earn_500_desc: '전투에서 500 골드를 획득하세요.',
      weekly_monster_collector: '마스터 콜렉터',
      weekly_monster_collector_desc: '이번 주에 총 10마리의 와일더를 포획하세요.',
      weekly_win_20: '전투 마라톤',
      weekly_win_20_desc: '전투에서 20번 승리하세요.',
      weekly_win_50: '그랜드 챔피언',
      weekly_win_50_desc: '전투에서 50번 승리하세요.',
      weekly_capture_5_rare: '희귀종 전문가',
      weekly_capture_5_rare_desc: '희귀(Rare) 등급 이상의 와일더를 5마리 포획하세요.',
      weekly_spend_5000: '시장 주도자',
      weekly_spend_5000_desc: '상점에서 5000 골드를 사용하세요.',
      weekly_evolve_3: '진화의 정점',
      weekly_evolve_3_desc: '와일더를 3번 진화시키세요.',
      weekly_earn_5000: '골드 타이쿤',
      weekly_earn_5000_desc: '전투에서 5000 골드를 획득하세요.',
      weekly_item_use_30: '지략가',
      weekly_item_use_30_desc: '아이템을 30번 사용하세요.',
      weekly_boss_slayer_3: '거인 학살자',
      weekly_boss_slayer_3_desc: '보스 와일더를 3마리 처치하세요.',
      weekly_spend_10000: '시장의 거물',
      weekly_spend_10000_desc: '상점에서 10000 골드를 사용하세요.',
      weekly_completionist: '퀘스트 중독자',
      weekly_completionist_desc: '이번 주에 다른 퀘스트를 10개 완료하세요.',
      collector_beginner: '초보 수집가',
      collector_beginner_desc: '3종류의 다른 와일더를 포획하세요.',
      collector_pro: '수집 전문가',
      collector_pro_desc: '20종류의 다른 와일더를 포획하세요.',
      collector_master: '전설의 탐험가',
      collector_master_desc: '50종류의 다른 와일더를 포획하세요.',
      gold_saver: '절약하는 테이머',
      gold_saver_desc: '현재 골드 1000을 보유하세요.',
      gold_millionaire: '황금 보관가',
      gold_millionaire_desc: '현재 골드 100,000을 보유하세요.',
      evolution_master: '변화의 군주',
      evolution_master_desc: '와일더를 총 10번 진화시키세요.',
      rare_hunter: '레어 헌터',
      rare_hunter_desc: '희귀(Rare) 등급 이상의 와일더를 포획하세요.',
      legendary_hunter: '전설 헌터',
      legendary_hunter_desc: '전설(Legendary) 등급의 와일더를 포획하세요.',
      faction_friend: '믿음직한 동료',
      faction_friend_desc: '아무 진영과의 평판 100을 달성하세요.',
      faction_hero: '진영의 영웅',
      faction_hero_desc: '아무 진영과의 평판 500을 달성하세요.',
      skill_unlock_10: '잠재력 개방',
      skill_unlock_10_desc: '스킬 노드를 총 10개 해제하세요.',
      skill_unlock_all: '한 우물 파기',
      skill_unlock_all_desc: '한 와일더의 모든 스킬 노드를 해제하세요.',
      win_streak_10: '거침없는 기세',
      win_streak_10_desc: '와일더를 잃지 않고 전투에서 10연승하세요.',
      win_streak_50: '투신',
      win_streak_50_desc: '전투에서 50연승하세요.',
      pesticide_specialist: '해충 박멸',
      pesticide_specialist_desc: '푸플을 100마리 처치하세요.',
    },
    skill_nodes: {
      p_speed_1: '빠른 발걸음',
      p_atk_1: '열기 어린 발톱',
      p_fire_special: '태양의 핵',
      p_dark_special: '달의 장막',
      d_def_1: '유동적 갑옷',
      d_ice: '한기 전이',
      d_mist: '안개 숙련',
      i_atk_1: '불꽃 갈기',
      i_atk_1_desc: '공격력을 5만큼 증가시킵니다.',
      i_blast: '용암 폭발',
      i_blast_desc: '불대문자 스킬을 해제합니다.',
      i_hp_1: '용암 피부',
      i_hp_1_desc: '최대 체력을 30만큼 증가시킵니다.',
      a_def_1: '물결 장막',
      a_def_1_desc: '방어력을 5만큼 증가시킵니다.',
      a_shard: '서리 송곳',
      a_shard_desc: '얼음 뭉치 스킬을 해제합니다.',
      a_healing: '정화',
      a_healing_desc: '최대 체력을 20만큼 증가시킵니다.',
      v_spd_1: '정전기 충전',
      v_spd_1_desc: '속도를 5만큼 증가시킵니다.',
      v_dash: '번개 돌진',
      v_dash_desc: '공격력을 8만큼 증가시킵니다.',
      v_crit: '전압 집중',
      v_crit_desc: '속도를 5만큼 증가시킵니다.',
    }
  },
  en: {
    ui: {
      loading: 'Loading EonTamers...',
      main_menu: 'Main Menu',
      start_game: 'Start Game',
      tamer_lvl: 'Tamer Level',
      gold: 'Gold',
      party: 'Party',
      skills: 'Skills',
      shop: 'Shop',
      quests: 'Quests',
      collection: 'Dex',
      debug: 'Debug',
      spirit_points: 'Spirit Points',
      back: 'Back',
      close: 'Close',
      purchase: 'Purchase',
      sell: 'Sell',
      current_stock: 'Current Stock',
      active: 'Active',
      completed: 'Completed',
      locked: 'Locked',
      unlocked: 'Unlocked',
      pending: 'Reward Pending',
      evolution_triggered: 'Evolution Triggered!',
      select_path: 'Select Evolution Path',
      not_now: 'Not now',
      required_item: 'Required Item',
      victory: 'Victory!',
      defeated: 'Defeated',
      captured: 'Captured!',
      escaped: 'Escaped!',
      tamer_commands: 'Tamer Commands',
      capture: 'Capture',
      hp: 'HP',
      atk: 'ATK',
      def: 'DEF',
      spd: 'SPD',
      reset_progress: 'Reset All Progress',
      dev_console: 'Dev Console',
      language: 'Language',
      boss_appeared: '⚠️ A Boss Has Appeared!',
      reputation: 'Reputation',
      factions: 'Factions',
      discount: 'Discount',
      save_game: 'Save Game',
      load_game: 'Load Game',
      confirm_save: 'Do you want to save your progress? This will overwrite your existing save.',
      confirm_load: 'Do you want to load your previous save? Current progress will be lost.',
      save_success: 'Game Saved Successfully!',
      save_failed: 'Save Failed',
      load_success: 'Load Complete!',
      no_save: 'No save data found.',
      back_to_lobby: 'Return to Lobby',
      quota_exceeded: 'Storage Quota Exceeded',
      storage_unavailable: 'Storage Unavailable',
      settings: 'Settings',
      claim_reward: 'Claim Rewards',
      quest_completed: 'Quest Completed!',
      inventory: 'Inventory',
      incubator: 'Incubator',
      no_items: 'No items to use.',
      use_item: 'Use Item',
      choose_tamer: 'Choose Tamer',
      choose_starter: 'Choose Starter Wilder',
      select_hero: 'Select Hero',
      confirm_selection: 'Confirm Selection',
      warrior_desc: 'Brave warrior, boasts high attack power.',
      scholar_desc: 'Wise scholar, excels in strategic combat.',
      mystic_desc: 'Mystic practitioner, handles spiritual forces.',
      ranger_desc: 'Agile scout, overwhelms enemies with speed.',
      hp_restored: 'Restored {amount} HP!',
      hp_full: 'HP is already full',
      item_used: 'Used {item}!',
      // Phase 4
      achievements: 'Achievements',
      achievement_unlocked: 'Achievement Unlocked!',
      claim: 'Claim',
      claimed: 'Claimed',
      progress: 'Progress',
      all: 'All',
      daily_login: 'Daily Login',
      login_streak: 'Login Streak',
      consecutive_days: '{days}-Day Streak',
      day: 'Day {day}',
      todays_reward: "Today's Reward",
      expeditions: 'Expeditions',
      start_expedition: 'Start Expedition',
      select_monsters: 'Select Monsters',
      selected: 'Selected',
      time_remaining: 'Time Remaining',
      duration: 'Duration',
      expedition_complete: 'Expedition Complete!',
      claim_rewards: 'Claim Rewards',
      available: 'Available',
      active_expeditions: 'Active Expeditions',
      requirements: 'Requirements',
      rewards: 'Rewards',
      monsters_required: '{count} Monster(s) Required',
      level_required: 'LV.{level}+',
      type_required: '{type} Type Required',
    },
    characters: {
      leo: 'Leo',
      ken: 'Ken',
      elara: 'Elara',
      zoe: 'Zoe'
    },
    roles: {
      warrior: 'Warrior',
      scholar: 'Scholar',
      mystic: 'Mystic',
      ranger: 'Ranger'
    },
    factions: {
      [FactionType.EMBER_CLAN]: 'Ember Clan',
      [FactionType.TIDE_WATCHERS]: 'Tide Watchers',
      [FactionType.STORM_HERDERS]: 'Storm Herders',
      [FactionType.GLOOM_STALKERS]: 'Gloom Stalkers',
      [FactionType.GLADE_KEEPERS]: 'Glade Keepers',
    },
    rep_tiers: {
      hated: 'Hated',
      hostile: 'Hostile',
      neutral: 'Neutral',
      friendly: 'Friendly',
      honored: 'Honored',
      exalted: 'Exalted',
    },
    achievement_categories: {
      combat: 'Combat',
      collection: 'Collection',
      progression: 'Progression',
      economy: 'Economy',
    },
    species: {
      pyrocat: 'Pyrocat',
      flarelion: 'Flarelion',
      droplet: 'Droplet',
      mistlynx: 'Mistlynx',
      lunacat: 'Lunacat',
      thunderhoof: 'Thunderhoof',
      puffle: 'Puffle',
      ignis: 'Ignis',
      flarehide: 'Flarehide',
      volcadragon: 'Volcadragon',
      aqualo: 'Aqualo',
      serpentform: 'Serpentform',
      krakenwhale: 'Krakenwhale',
      voltwing: 'Voltwing',
      stormhawk: 'Stormhawk',
      thundernebula: 'Thundernebula',
    },
    items: {
      potion: 'Small Potion',
      potion_desc: 'Heals 20 HP.',
      capture_orb: 'Capture Orb',
      capture_orb_desc: 'Used to capture wild wilders.',
      sun_stone: 'Sun Stone',
      sun_stone_desc: 'Evolutionary item.',
      moon_stone: 'Moon Stone',
      moon_stone_desc: 'Evolutionary item.',
      blazing_fang: 'Blazing Fang',
      blazing_fang_desc: 'Boosts Fire attribute attack.',
      blazing_fang_lore: 'The essence remains after a thousand hunts.',
      tidal_blade: 'Tidal Blade',
      tidal_blade_desc: 'Boosts Water attribute attack.',
      tidal_blade_lore: 'A blade infused with the cold of the deep sea.',
      storm_scepter: 'Storm Scepter',
      storm_scepter_desc: 'Boosts Electric attribute speed.',
      storm_scepter_lore: 'A crackling energy flows through it.',
      iron_shell: 'Iron Shell',
      iron_shell_desc: 'Greatly increases defense.',
      iron_shell_lore: 'Heavy but reliable protection.',
      ember_plate: 'Ember Plate',
      ember_plate_desc: 'Fire attribute exclusive armor.',
      ember_plate_lore: 'Converts heat into energy.',
      void_armor: 'Void Armor',
      void_armor_desc: 'Ultimate armor containing shadow power.',
      void_armor_lore: 'The abyss will watch over you.',
      wind_pendant: 'Wind Pendant',
      wind_pendant_desc: 'Increases speed.',
      wind_pendant_lore: 'The lightness of a breeze.',
      heart_stone: 'Heart Stone',
      heart_stone_desc: 'Increases maximum HP.',
      heart_stone_lore: 'Strengthens the heartbeat.',
      monster_core: 'Wilder Core',
      monster_core_desc: 'Core material for crafting.',
      mystic_powder: 'Mystic Powder',
      mystic_powder_desc: 'Powder for magical processing.',
      hardened_bone: 'Hardened Bone',
      hardened_bone_desc: 'Material for equipment reinforcement.',
      spirit_essence: 'Spirit Essence',
      spirit_essence_desc: 'Extremely rare spiritual material.',
      ancient_scrap: 'Ancient Scrap',
      ancient_scrap_desc: 'Legacy of forgotten technology.',
    },
    skills: {
      scratch: 'Scratch',
      scratch_desc: 'A basic physical scratch.',
      ember: 'Ember',
      ember_desc: 'A small burst of flame.',
      tackle: 'Tackle',
      tackle_desc: 'A basic physical charge.',
      bubble: 'Bubble',
      bubble_desc: 'Shoots a spray of bubbles.',
      fire_blast: 'Fire Blast',
      fire_blast_desc: 'A devastating inferno wave.',
      dark_pulse: 'Dark Pulse',
      dark_pulse_desc: 'Releases a shadow energy wave.',
      ice_shard: 'Ice Shard',
      ice_shard_desc: 'Fire freezing shards rapidly.',
      cheer: 'Cheer',
      cheer_desc: 'Boost ATK by 5 for 10s.',
      first_aid: 'First Aid',
      first_aid_desc: 'Heal monster for 25 HP.',
      rally: 'Rally',
      rally_desc: 'Cleanse all skill cooldowns.',
      // LEO
      leo_rage: 'Rage Shout',
      leo_rage_desc: 'Boost ATK by 10 for 20s.',
      leo_iron: 'Iron Will',
      leo_iron_desc: 'Boost DEF by 10 for 20s.',
      leo_war_cry: 'War Cry',
      leo_war_cry_desc: 'Boost ATK by 30 for 20s.',
      leo_pride: "Lion's Pride",
      leo_pride_desc: 'Boost ATK/DEF by 20 for 30s.',
      leo_king: 'King of Beasts',
      leo_king_desc: 'Boost ATK by 60 for 15s.',
      // KEN
      ken_eye: 'Tactical Eye',
      ken_eye_desc: 'Boost SPD by 15 for 20s.',
      ken_scan: 'Weakness Scan',
      ken_scan_desc: 'Enemy DEF -15 for 20s.',
      ken_command: 'Precise Command',
      ken_command_desc: 'Boost SPD by 30 for 20s.',
      ken_strategy: 'Grand Strategy',
      ken_strategy_desc: 'Boost ATK by 25 for 30s.',
      // ELARA
      elara_heal: 'Spirit Heal',
      elara_heal_desc: 'Heal monster for 50 HP.',
      elara_regen: 'Inner Peace',
      elara_regen_desc: 'Cleanse and regen 10 HP/s for 10s.',
      elara_flow: 'Spirit Flow',
      elara_flow_desc: 'Heal monster for 150 HP.',
      // ZOE
      zoe_wind: 'Tailwind',
      zoe_wind_desc: 'Boost SPD by 20 for 20s.',
      zoe_lock: 'Target Lock',
      zoe_lock_desc: 'Boost ATK by 15 for 10s.',
      zoe_hurricane: 'Hurricane',
      zoe_hurricane_desc: 'Boost SPD by 40 for 20s.',
    },
    quests: {
      first_capture: 'First Capture',
      first_capture_desc: 'Capture your first Wilder.',
      reach_level_5: 'Growing Tamer',
      reach_level_5_desc: 'Reach Tamer level 5.',
      defeat_lunacat: 'Defeat Lunacat',
      defeat_lunacat_desc: 'Defeat the elusive Lunacat that appears at night!',
      story_capture_5: 'Growing Collection',
      story_capture_5_desc: 'Capture 5 different species of monsters.',
      reach_level_10: 'Tamer Apprentice',
      reach_level_10_desc: 'Reach Tamer level 10.',
      reach_level_20: 'Tamer Professional',
      reach_level_20_desc: 'Reach Tamer level 20.',
      defeat_boss_flarelion: 'Trial of Fire',
      defeat_boss_flarelion_desc: 'Defeat the Alpha Flarelion (World Boss).',
      defeat_boss_krakenwhale: 'Deep Sea Terror',
      defeat_boss_krakenwhale_desc: 'Defeat the Alpha Krakenwhale (World Boss).',
      reach_level_50: 'Legendary Tamer',
      reach_level_50_desc: 'Reach the maximum level 50.',
      daily_win_3: 'Morning Drill',
      daily_win_3_desc: 'Win 3 battles.',
      daily_win_5: 'Battle Hardened',
      daily_win_5_desc: 'Win 5 battles.',
      daily_capture_1: 'Quick Catch',
      daily_capture_1_desc: 'Capture 1 Wilder.',
      daily_capture_3: 'Recruitment Drive',
      daily_capture_3_desc: 'Capture 3 Wilders.',
      daily_item_use: 'Prep Time',
      daily_item_use_desc: 'Use 5 items.',
      daily_item_use_10: 'Inventory Check',
      daily_item_use_10_desc: 'Use 10 items.',
      daily_spend_100: 'Local Customer',
      daily_spend_100_desc: 'Spend 100 gold at the shop.',
      daily_spend_500: 'Big Spender',
      daily_spend_500_desc: 'Spend 500 gold at the shop.',
      daily_win_fire: 'Extinguish Flames',
      daily_win_fire_desc: 'Defeat 3 Fire type Wilders.',
      daily_win_water: 'Tame the Tides',
      daily_win_water_desc: 'Defeat 3 Water type Wilders.',
      daily_win_grass: 'Weed Out',
      daily_win_grass_desc: 'Defeat 3 Grass type Wilders.',
      daily_win_electric: 'Ground the Current',
      daily_win_electric_desc: 'Defeat 3 Electric type Wilders.',
      daily_win_neutral: 'Balance of Power',
      daily_win_neutral_desc: 'Defeat 3 Neutral type Wilders.',
      daily_win_dark_light: 'Twilight Duel',
      daily_win_dark_light_desc: 'Defeat 3 Dark or Light type Wilders.',
      daily_earn_500: 'Profit Hunter',
      daily_earn_500_desc: 'Earn 500 gold from battles.',
      weekly_monster_collector: 'Master Collector',
      weekly_monster_collector_desc: 'Capture total 10 monsters this week.',
      weekly_win_20: 'Battle Marathon',
      weekly_win_20_desc: 'Win 20 battles.',
      weekly_win_50: 'Grand Champion',
      weekly_win_50_desc: 'Win 50 battles.',
      weekly_capture_5_rare: 'Rare Specialist',
      weekly_capture_5_rare_desc: 'Capture 5 Rare or higher rarity Wilders.',
      weekly_spend_5000: 'Market Roller',
      weekly_spend_5000_desc: 'Spend 5000 gold at the shop.',
      weekly_evolve_3: 'Evolutionary Peak',
      weekly_evolve_3_desc: 'Evolve 3 Wilders.',
      weekly_earn_5000: 'Gold Tycoon',
      weekly_earn_5000_desc: 'Earn 5000 gold from battles.',
      weekly_item_use_30: 'Resourceful',
      weekly_item_use_30_desc: 'Use 30 items.',
      weekly_boss_slayer_3: 'Titan Slayer',
      weekly_boss_slayer_3_desc: 'Defeat 3 Alpha Wilders (Bosses).',
      weekly_spend_10000: 'Market Titan',
      weekly_spend_10000_desc: 'Spend 10000 gold at the shop.',
      weekly_completionist: 'Quest Addict',
      weekly_completionist_desc: 'Complete 10 other quests this week.',
      collector_beginner: 'Beginner Collector',
      collector_beginner_desc: 'Capture 3 different species of monsters.',
      collector_pro: 'Collection Expert',
      collector_pro_desc: 'Capture 20 different species of monsters.',
      collector_master: 'Grand Master Explorer',
      collector_master_desc: 'Capture 50 different species of monsters.',
      gold_saver: 'Thrifty Tamer',
      gold_saver_desc: 'Accumulate 1000 gold in your wallet.',
      gold_millionaire: 'Gold Hoarder',
      gold_millionaire_desc: 'Accumulate 100,000 gold in your wallet.',
      evolution_master: 'Lord of Change',
      evolution_master_desc: 'Successfully evolve 10 monsters.',
      rare_hunter: 'Rare Hunter',
      rare_hunter_desc: 'Capture a monster with "Rare" or higher rarity.',
      legendary_hunter: 'Legendary Hunter',
      legendary_hunter_desc: 'Capture a monster with "Legendary" rarity.',
      faction_friend: 'Trusted Ally',
      faction_friend_desc: 'Reach 100 Reputation with any faction.',
      faction_hero: 'Faction Hero',
      faction_hero_desc: 'Reach 500 Reputation with any faction.',
      skill_unlock_10: 'Power Awakening',
      skill_unlock_10_desc: 'Unlock 10 skill nodes.',
      skill_unlock_all: 'Master of One',
      skill_unlock_all_desc: 'Unlock all skill nodes for a single Wilder.',
      win_streak_10: 'Unstoppable',
      win_streak_10_desc: 'Win 10 battles in a row without losing a Wilder.',
      win_streak_50: 'God of Battle',
      win_streak_50_desc: 'Win 50 battles in a row.',
      pesticide_specialist: 'Pesticide Specialist',
      pesticide_specialist_desc: 'Defeat 100 Puffles.',
    },
    skill_nodes: {
      p_speed_1: 'Swift Paws',
      p_atk_1: 'Heated Claws',
      p_fire_special: 'Solar Core',
      p_dark_special: 'Lunar Shroud',
      d_def_1: 'Fluid Armor',
      d_ice: 'Cold Snap',
      d_mist: 'Mist Mastery',
      i_atk_1: 'Fire Mane',
      i_atk_1_desc: 'Increases Attack by 5.',
      i_blast: 'Magma Burst',
      i_blast_desc: 'Unlocks Fire Blast skill.',
      i_hp_1: 'Lava Skin',
      i_hp_1_desc: 'Increases Max HP by 30.',
      a_def_1: 'Water Veil',
      a_def_1_desc: 'Increases Defense by 5.',
      a_shard: 'Frost Spike',
      a_shard_desc: 'Unlocks Ice Shard skill.',
      a_healing: 'Purification',
      a_healing_desc: 'Increases Max HP by 20.',
      v_spd_1: 'Static Charge',
      v_spd_1_desc: 'Increases Speed by 5.',
      v_dash: 'Spark Dash',
      v_dash_desc: 'Increases Attack by 8.',
      v_crit: 'Voltage Focus',
      v_crit_desc: 'Increases Speed by 5.',
    }
  }
};

export const getTranslation = (lang: Language) => {
  return strings[lang] || strings.ko;
};

export const getReputationTier = (points: number, lang: Language) => {
  const t = getTranslation(lang).rep_tiers;
  if (points >= 1000) return t.exalted;
  if (points >= 500) return t.honored;
  if (points >= 100) return t.friendly;
  if (points >= -100) return t.neutral;
  if (points >= -500) return t.hostile;
  return t.hated;
};

export const getFactionDiscount = (points: number): number => {
  if (points >= 1000) return 0.20; // 20%
  if (points >= 500) return 0.10; // 10%
  if (points >= 100) return 0.05; // 5%
  return 0;
};
